name: Electron Forge CI

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Node - ${{ matrix.node_version }} OS - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node JS Version
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}

      - name: npm ci, Electron Forge make
        run: |
          npm ci
          npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

